/**
 * QR Review — Mock Reviews Database
 * 500+ pre-written reviews for BP International (wholesale bulk supplier)
 * Used as fallback when AI generation fails
 *
 * Categories: gifts, decorations, photo frames, flex banners,
 * flower items, handicrafts, crystal frames, stationery
 */

const MOCK_REVIEWS = {
  // ─── 5-Star Reviews (170 reviews) ───
  5: [
    "BP International never disappoints when it comes to bulk orders. The quality of their photo frames is consistently top-notch.",
    "We've been sourcing decorations from BP International for years now. Their prices and quality keep us coming back every season.",
    "Ordered crystal frames in bulk for our retail store and the clarity on each piece was stunning. Highly recommended for resellers.",
    "The stationery collection here is massive. Got everything we needed for our school supply business in one order.",
    "Fantastic range of handicrafts at wholesale prices. Our customers absolutely love the unique designs they carry.",
    "BP International has the best flex banner materials in the market. Print quality comes out crisp every single time.",
    "Their flower items collection is beautiful and well-made. Perfect for our event planning business supplies.",
    "Got a huge order of gift items delivered on time with perfect packaging. Not a single item was damaged.",
    "The variety of decorations they stock is unmatched. From festive to everyday decor, they have it all.",
    "Crystal frames from BP International are a bestseller in our shop. The quality speaks for itself.",
    "Reliable wholesale supplier with fair prices. We order stationery monthly and have never had an issue.",
    "Their handicraft selection is one of the best I've seen. Great for unique gift shop inventory.",
    "Ordered flex banners for a corporate event and the results were professional-grade. Very satisfied.",
    "Photo frames come in so many styles and sizes. Our customers always find what they're looking for.",
    "BP International's gift items have great markup potential. The quality looks premium but the wholesale price is very reasonable.",
    "Bulk ordering is seamless with them. Quick communication, accurate invoicing, and fast delivery.",
    "The flower arrangements and artificial flower items they carry look incredibly realistic. Great for decoration businesses.",
    "We switched to BP International for our stationery supply and noticed better quality at lower cost.",
    "Their decoration items are trendy and updated regularly. They keep up with the latest styles.",
    "Crystal frames make perfect wedding favors. We ordered 200 pieces and every single one was flawless.",
    "Been a loyal customer for three years. The consistency in their product quality is what sets them apart.",
    "The handicraft items we sourced from BP International sold out in our store within a week. Amazing products.",
    "Photo frames in bulk were delivered ahead of schedule. The attention to detail in packaging was impressive.",
    "Their flex banner printing services are quick and affordable. Great for small business owners like us.",
    "Gift items from BP International always get positive feedback from our retail customers. Top quality stuff.",
    "Ordered decorations for multiple stores and the pricing was incredibly competitive for the quality offered.",
    "The stationery range is comprehensive — pens, notebooks, folders, everything. One-stop shop for our needs.",
    "Flower items arrived fresh-looking and vibrant. The colors were exactly as shown in the catalog.",
    "BP International is our go-to for crystal frames. The finish and clarity are always premium grade.",
    "Their bulk order discounts are genuinely helpful for small businesses trying to keep costs down.",
    "Handicrafts sourced from here have a unique artisan feel that our boutique customers really appreciate.",
    "Fast turnaround on flex banners with vivid colors. Our marketing materials look professional every time.",
    "The photo frame collection ranges from modern minimalist to ornate traditional — something for every market.",
    "Gift items packaging was retail-ready. Saved us time on repackaging for our store shelves.",
    "Decoration quality from BP International exceeds what you'd expect at wholesale pricing.",
    "Their stationery items are durable and well-made. No complaints from any of our school supply customers.",
    "Ordered flower decorations for a banquet hall setup. Everything looked elegant and held up throughout the event.",
    "Crystal frames with engraving options are a game-changer for personalized gift orders. Love this supplier.",
    "BP International handles large orders with the same care as small ones. That's what makes them special.",
    "The handicraft collection has genuine handmade pieces that stand out from mass-produced alternatives.",
    "Flex banners were weather-resistant and still look great months after installation. Excellent material quality.",
    "Photo frames arrive with protective wrapping on each piece. Shows they care about their products reaching us intact.",
    "Their gift item catalog is updated seasonally which helps us stay current with trending products.",
    "Decoration items from BP International add a premium touch to any space. Our clients always notice.",
    "Stationery in bulk at these prices is hard to find elsewhere. Consistent quality order after order.",
    "Flower items for artificial garlands were exactly what we needed. The colors were vibrant and realistic.",
    "Crystal frames as corporate gifts were a hit. The presentation quality impressed all our clients.",
    "Reliable shipping even for heavy bulk orders. Everything arrives well-packaged and on time.",
    "Handicrafts from BP International have helped our boutique stand out from competitors.",
    "Flex banner materials are easy to work with and produce sharp, professional results every time.",
    "Photo frames in vintage style are our bestseller and BP International keeps them well-stocked.",
    "Bulk gift item pricing here is the most competitive we've found after comparing multiple suppliers.",
    "The decoration range for weddings is stunning. Elegant pieces at wholesale prices.",
    "Stationery products have a premium feel that our customers appreciate. Great value for money.",
    "Flower items collection includes everything from single stems to full arrangement supplies.",
    "Crystal frames are beautifully designed. The light-catching effect makes them look much more expensive.",
    "We've recommended BP International to several other retailers. Everyone has been equally satisfied.",
    "Handicraft items have authentic craftsmanship that adds real value to our product offerings.",
    "Flex banners for outdoor advertising held up perfectly through monsoon season. Very durable material.",
    "Photo frames with custom sizes are available on request which is a huge plus for our business.",
    "Gift items arrived earlier than expected with a detailed packing list. Professional service all around.",
    "Decoration supplies for our event company are always sourced from BP International. Never let us down.",
    "Stationery sets make great corporate gift bundles. The quality justifies premium pricing in our store.",
    "Flower decorations look so real that our customers often ask if they're fresh flowers.",
    "Crystal photo frames are our most requested gift item and BP International never runs out of stock.",
    "Wholesale pricing here actually makes sense. No hidden charges or surprise costs on bulk orders.",
    "Handicraft wall hangings from BP International are statement pieces. Always draw compliments.",
    "Flex banner printing turnaround is faster than any other supplier we've tried in the region.",
    "Photo frame quality is consistent across every batch we order. No duds, no rejects.",
    "Gift items are thoughtfully designed with current market trends in mind. Smart product curation.",
    "Decoration pieces for corporate offices have been well-received. Clean, modern aesthetics.",
    "Stationery products are eco-friendly which is a big selling point for our environmentally conscious customers.",
    "Flower items for wedding decoration supply were beautiful and exactly matched the sample photos.",
    "Crystal frames with LED backlighting are a unique offering we haven't found elsewhere.",
    "BP International treats every customer with respect regardless of order size. Great business ethics.",
    "Handicrafts are genuinely made by artisans. You can see the quality and attention in every piece.",
    "Flex banners for storefront signage have been durable and color-fast even in direct sunlight.",
    "Photo frames in metallic finishes are a hot seller. The quality and shine are impressive.",
    "Gift wrapping supplies from BP International are premium grade. Makes our products look upscale.",
    "Decoration items for Diwali season were beautiful and arrived well before the festival rush.",
    "Stationery for corporate branding with logo imprint options is a great service they offer.",
    "Flower arrangements for table centerpieces were classy and well-constructed. Durable too.",
    "Crystal frames as anniversary gifts are always appreciated. The clarity and sparkle are mesmerizing.",
    "Partnering with BP International was one of the best decisions for our retail business growth.",
    "Handicraft items have strong cultural appeal that resonates with tourists and collectors alike.",
    "Flex banners resist tearing and fading better than materials from our previous supplier.",
    "Photo frames arrived with hanging hardware included. Small detail but saves us time and hassle.",
    "Gift baskets assembled with BP International products look professionally curated.",
    "Decoration lighting items from their collection add ambiance to any event setup.",
    "Stationery bundles for back-to-school season sold out fast. Will definitely reorder.",
    "Flower items including artificial roses and lilies look remarkably natural. Excellent craftsmanship.",
    "Crystal frames are the perfect blend of elegance and affordability for our gift shop.",
    "Their customer service team is responsive and helpful with product recommendations for our market.",
    "Handicraft pieces make excellent home decor items. Our customers keep coming back for more.",
    "Flex banners for trade shows looked spectacular. Professional presentation at wholesale cost.",
    "Photo frames in acrylic and wood options give us good variety to offer our customers.",
    "Gift items with festival themes sell incredibly well. BP International always has seasonal stock ready.",
    "Decoration supplies are well-categorized in their catalog making it easy to find what we need.",
    "Stationery quality has been uniformly excellent across all our orders spanning two years.",
    "Flower garlands for temple supply business are beautiful and competitively priced here.",
    "Crystal frames with personalized engraving service add significant value to our gift offerings.",
    "We trust BP International for all our bulk decoration needs. They've earned our loyalty.",
    "Handicraft boxes and organizers are both functional and decorative. Unique products.",
    "Flex banner installations look crisp and professional. The material handles well during setup.",
    "Photo frames are well-finished with no rough edges or defects. Quality control is solid.",
    "Gift items come in attractive packaging that our customers appreciate. Adds to the unboxing experience.",
    "Decoration items for restaurant interiors were stylish and received great customer feedback.",
    "Stationery items arrive shrink-wrapped and organized. Ready for immediate shelving in our store.",
    "Flower items for craft projects are versatile and hold up well during assembly.",
    "Crystal frames catch light beautifully and create an elegant display in our showroom.",
    "BP International's wholesale prices allow us to maintain healthy margins while offering fair retail prices.",
    "Handicraft items from different regions of Nepal are unique and tell beautiful cultural stories.",
    "Flex banners are our primary advertising material and BP International delivers consistently.",
    "Photo frames make excellent housewarming gifts. Our customers buy them in sets regularly.",
    "Gift item variety changes seasonally keeping our inventory fresh and interesting for repeat customers.",
    "Decoration pieces for office spaces are modern and professional. Perfect for corporate clients.",
    "Stationery brand quality from BP International competes with much more expensive retail options.",
    "Flower items in silk finish are luxurious looking and long-lasting. Worth every rupee.",
    "Crystal frames as religious gift items have been very popular with our customer base.",
    "Their packing standards are professional. We've never received a damaged shipment in dozens of orders.",
    "Handicraft jewelry boxes are beautifully made and always popular during the gifting seasons.",
    "Flex banners with full color printing are vibrant and eye-catching. Great for promotional events.",
    "Photo frames with multi-photo display options are trending and BP International stocks them well.",
    "Gift items quality is noticeably better than other wholesale suppliers in the market.",
    "Decoration items for baby shower events were adorable and well-made. Happy customers every time.",
    "Stationery pouches and pencil cases are stylish and functional. A hit with our school-going customers.",
    "Flower items for seasonal decorations always arrive in time for us to prepare our displays.",
    "Crystal frames as trophy alternatives for small awards ceremonies look impressive and professional.",
    "BP International makes bulk ordering simple with their streamlined process and clear pricing.",
    "Handicraft table runners and coasters are beautifully woven. They add charm to dining setups.",
    "Flex banners for real estate signage have been durable through all weather conditions.",
    "Photo frames collection includes trendy geometric and minimalist designs that sell quickly.",
    "Gift items sourced here consistently generate positive reviews from our end customers.",
    "Decoration supply chain has been reliable throughout festival seasons when demand peaks.",
    "Stationery notebooks with premium paper quality are popular with journaling enthusiasts.",
    "Flower baskets pre-arranged from BP International save us assembly time and look professional.",
    "Crystal frames are packaged individually in velvet pouches. Adds a luxury feel to each sale.",
    "Their team understands wholesale dynamics and offers practical advice for our retail business.",
    "Handicraft lamp shades add a warm, artisan touch to home decor. Unique inventory for our store.",
    "Flex banners maintain color accuracy which is crucial for brand-specific printing jobs.",
    "Photo frames in rose gold finish have been our top seller this year. Beautiful products.",
    "Gift hamper components from BP International allow us to create custom gift sets efficiently.",
    "Decoration candles and holders are elegant and well-priced for our event decoration business.",
    "Stationery markers and art supplies are high quality. Art students specifically request them.",
    "Flower crowns and headband materials are popular for wedding photo shoots and events.",
    "Crystal frames with clock inserts are functional and decorative. A unique gift item.",
    "We appreciate their transparent pricing structure. No surprises on the final invoice.",
    "Handicraft wind chimes from BP International are melodious and beautifully crafted.",
    "Flex banner stands and display units are sturdy and portable. Great for exhibitions.",
    "Photo frames with glass protection are premium and give a professional gallery-like finish.",
    "Gift tags and accessories from their stationery line complete our packaging needs perfectly.",
    "Decoration ribbons and bows are high quality and available in every color imaginable.",
    "Stationery organizers for desks are practical and have a clean modern design.",
    "Flower pots and vase collection is diverse. From ceramic to metallic, they stock everything.",
    "Crystal frame quality at BP International's price point is simply unbeatable in the market.",
    "Their inventory management is impressive. Items we need are almost always in stock.",
    "Handicraft wall clocks are functional art pieces that our customers buy as statement decor.",
    "Flex banners for political campaign signage were delivered on a tight deadline without issues.",
    "Photo frames in sets of 6 and 12 are convenient for wall gallery kits we sell.",
    "Gift wrapping paper from BP International has premium texture and beautiful print patterns.",
    "Decoration pieces for Tihar festival were colorful and authentic. Sold out within days.",
    "Stationery pen sets make excellent corporate gifts. Professional look with budget-friendly pricing.",
    "Flower arrangements for funeral services are tasteful and respectfully designed.",
    "Crystal awards and trophies from BP International are used by multiple organizations we supply to.",
    "The team at BP International always goes the extra mile to meet our deadlines. True professionals.",
    "Every reorder we place confirms why BP International is our primary wholesale partner.",
    "Decoration items for New Year events were dazzling. Sparkle and glitter items were top quality.",
    "Stationery planners and diaries with premium binding are a strong seller in our store.",
    "Flower items in pastel tones are perfect for spring collections. Very popular with event planners.",
    "Crystal frames as retirement gifts were elegant and memorable. The recipients were thrilled.",
    "Their wholesale MOQs are reasonable even for smaller retail shops just starting out.",
    "Handicraft masks and wall art pieces have strong cultural significance and craftsmanship."
  ],

  // ─── 4-Star Reviews (170 reviews) ───
  4: [
    "Good selection of photo frames at BP International. A few more modern designs would be nice but overall very satisfied.",
    "Bulk stationery orders are reliable here. Delivery was a day late once but the quality made up for it.",
    "Decent range of handicrafts. The pricing is competitive and most items meet our quality expectations.",
    "Flex banners from BP International are solid quality. Would love faster turnaround on rush orders though.",
    "Gift items are generally well-made. Some packaging could be a bit sturdier for shipping purposes.",
    "Crystal frames are beautiful but the size options could be more varied. What they have is excellent quality.",
    "Good wholesale prices on decorations. Catalog navigation could be improved to find items faster.",
    "Flower items are well-made and realistic. A wider color palette would help us serve more customers.",
    "Stationery quality is good for the price point. Some items are outstanding while others are just adequate.",
    "Photo frames arrived well-packaged. The glass on a couple was slightly scratched but they replaced them quickly.",
    "Handicraft selection is interesting. It would be great if they added more contemporary designs alongside traditional ones.",
    "Flex banner materials are durable and print well. Customer service is helpful but sometimes slow to respond.",
    "Decoration items for events are pretty good. Some pieces could have better finishing on the edges.",
    "Gift baskets components are decent quality. The variety is good enough to create attractive gift sets.",
    "Crystal frames look lovely. Delivery tracking information could be more detailed for larger orders.",
    "Good bulk prices on stationery. Would appreciate a loyalty discount program for regular customers.",
    "Flower garlands are realistic looking. The wire stems could be a bit more flexible for arranging.",
    "Photo frames in wooden finish are nice. Some had minor color variations but still looked good overall.",
    "Handicraft items have charm. A few pieces showed minor quality inconsistencies but nothing deal-breaking.",
    "Flex banners hold up well outdoors. The print resolution could be slightly higher for close-up viewing.",
    "Decoration candles are attractive. The scent options are limited but the visual quality is great.",
    "Gift items are solid choices for our store. Some product descriptions in the catalog could be more accurate.",
    "Crystal frames with engraving turned out well. The font options could be expanded a bit.",
    "Stationery sets are good value. The ruler quality could be improved but pens and pencils are excellent.",
    "Flower items in the premium range are stunning. The basic range is adequate but not as impressive.",
    "Photo frames come in good variety. Wish they had more custom size options available off the shelf.",
    "Handicraft wall art is beautiful. The hanging hardware included could be stronger for heavier pieces.",
    "Flex banner stands are functional. The assembly instructions could be clearer for first-time users.",
    "Decoration items for Christmas were good. A few items didn't match the catalog photos exactly.",
    "Gift wrapping supplies are decent quality. The tape selection could be broader.",
    "Crystal frames arrived safely. Would be nice to have a preview tool for the engraving before ordering.",
    "Stationery brand is solid. Some notebook binding could be tighter to prevent pages coming loose.",
    "Flower pots are attractive. The drainage holes on some models were positioned oddly.",
    "Photo frames in acrylic are clear and modern. They scratch a bit easily so handling needs care.",
    "Handicraft items are unique. Some are delicate so shipping smaller items needs extra padding.",
    "Flex banners for indoor use are perfect. Outdoor ones fade a little faster than expected.",
    "Decoration lighting is nice. Battery life on some LED items could be longer.",
    "Gift items overall are good value. The premium line is definitely worth the extra cost.",
    "Crystal frames are elegant. The base stands could be slightly wider for better stability.",
    "Stationery coloring supplies are good. The marker ink could be more vibrant in some colors.",
    "Flower items for centerpieces work well. Some stems are a bit short for taller vases.",
    "Photo frames with digital printing look nice. The resolution could be crisper on smaller frames.",
    "Handicraft jewelry is interesting. Clasps on some pieces could be more secure.",
    "Flex banner printing is reliable. Color matching to our brand guidelines was close but not perfect.",
    "Decoration pieces for modern interiors are good. A few items felt lightweight for their size.",
    "Gift tags and cards from the stationery section are pretty. Print quality is good on most.",
    "Crystal frames catch light beautifully. The gift box packaging could be more luxurious.",
    "Stationery folders are functional. The color range is a bit limited compared to competitors.",
    "Flower arrangements come well-secured for shipping. A few petals were bent but mostly fine.",
    "Photo frames with multiple openings are popular. The back panel could be easier to access.",
    "Handicraft bookends are charming. A few pairs had slight size differences between the two pieces.",
    "Flex banners with eyelets are well-finished. The spacing between eyelets could be more consistent.",
    "Decoration items are trendy and current. Restocking of popular items could be faster.",
    "Gift items during festive season are in high demand. Pre-ordering system would be helpful.",
    "Crystal frames in larger sizes are impressive. Smaller ones could have more design variety.",
    "Stationery for kids section is colorful and fun. Age-appropriate labeling would be a nice addition.",
    "Flower items artificial range is broad. Some budget items look noticeably artificial up close.",
    "Photo frames with engraving are thoughtful gifts. The turnaround time could be shorter.",
    "Handicraft coasters are practical and pretty. Cork backing on a few was slightly uneven.",
    "Flex banners are weather-resistant as promised. Color vibrancy holds up well for several months.",
    "Decoration supplies for weddings are elegant. A wedding-specific catalog section would help.",
    "Gift items wholesale pricing is fair. Minimum order quantities could be lowered for new customers.",
    "Crystal frames look premium. The weight is just right — feels substantial without being too heavy.",
    "Stationery pen quality is reliable. Ink flow is smooth on most pens, a few need slight pressure.",
    "Flower items for festive decoration are lovely. More traditional festival-specific options would be great.",
    "Photo frames ship quickly for standard sizes. Custom orders take a bit longer than quoted.",
    "Handicraft figurines are detailed and well-made. Some paint touch-ups could be neater.",
    "Flex banner material options are good. A sample swatch kit would help choose the right material.",
    "Decoration items are well-priced. Online ordering with real-time inventory would be convenient.",
    "Gift items quality control is mostly good. Occasional minor defects but always resolved by the team.",
    "Crystal frames with colored glass options are lovely. More color choices would be welcome.",
    "Stationery calculators and tech accessories are functional. Brand variety could be expanded.",
    "Flower items silk range is impressive. Synthetic range could use better textures.",
    "Photo frames arrived intact and looking good. Assembly for standing frames could be more intuitive.",
    "Handicraft storage boxes are beautiful. Hinge quality on some boxes could be sturdier.",
    "Flex banners for temporary events work well. Removal sometimes leaves minor residue.",
    "Decoration items for retail store displays are creative. Seasonal rotation timing is good.",
    "Gift items variety keeps our store interesting. More gender-neutral options would be appreciated.",
    "Crystal frames make great award alternatives. Etching precision is good on most pieces.",
    "Stationery whiteboard markers are effective. The eraser quality included with boards could improve.",
    "Flower items for hair accessories are delicate and pretty. Attachment clips could be stronger.",
    "Photo frames with matting options look professional. The matting colors available are somewhat limited.",
    "Handicraft dream catchers are popular sellers. The feather quality varies slightly between batches.",
    "Flex banners for vehicle wraps are serviceable. Specialized vehicle wrap materials would be a good addition.",
    "Decoration mirrors from BP International look elegant. Edge finishing could be more polished.",
    "Gift bags and tissue paper quality is nice. More size options for larger gifts would help.",
    "Crystal frames as corporate gifts received good feedback. Bulk customization turnaround could be faster.",
    "Stationery file organizers are practical. The labeling system could be more user-friendly.",
    "Flower petal scatters for events are pretty. The cleanup is a bit messy with some materials.",
    "Photo frames wholesale pricing is fair. Volume discount tiers could be more clearly communicated.",
    "Handicraft pottery items are charming. Glaze consistency varies a little between pieces.",
    "Flex banner grommets are sturdy. The spacing template for custom sizes would be helpful.",
    "Decoration cushion covers have nice prints. The fabric could be slightly thicker for premium feel.",
    "Gift wrapping accessories are functional. The bow-making supplies are good quality.",
    "Crystal frames for religious purposes are well-designed. More religious symbol options would be great.",
    "Stationery paper quality is good for writing. Printer compatibility information would be useful.",
    "Flower stems in bulk are reasonably priced. Sorting by stem length at the warehouse would help.",
    "Photo frames with clip-on stands are convenient. The clips could grip a bit tighter.",
    "Handicraft incense holders are beautifully designed. Some are a bit delicate for daily use.",
    "Flex banners with UV protection last well. The protection level could be more clearly rated.",
    "Decoration trays are stylish and functional. Non-slip bases would be a nice enhancement.",
    "Gift items for children's parties are fun and affordable. More age-specific categorization would help.",
    "Crystal frames reflection quality is good. Anti-glare options would be useful for brightly lit spaces.",
    "Stationery adhesive products work well. The range includes most common needs for office and craft.",
    "Flower bouquet wrapping materials are elegant. More eco-friendly options would be appreciated.",
    "Photo frames with built-in lighting are a cool product. Battery replacement access could be easier.",
    "Handicraft candle holders are atmospheric. Heat resistance could be better on painted finishes.",
    "Flex banners roll up neatly for storage. Carrying cases for rolled banners would be a nice add-on.",
    "Decoration wall stickers are colorful. Removal after long periods can be tricky on some surfaces.",
    "Gift boxes in premium range are excellent. The standard range boxes could have better closure.",
    "Crystal frames with floating effect design are modern and eye-catching. Great for contemporary spaces.",
    "Stationery stapler quality is good. Staple capacity could be higher on the standard models.",
    "Flower items for boutonnieres are well-crafted. Pin attachment mechanisms could be improved.",
    "Photo frames multipack deals offer good savings. The range of styles in multipacks could vary more.",
    "Handicraft place mats are attractive. Stain resistance on some materials could be better.",
    "Flex banners adhesive-backed options stick well initially. Long-term adhesion could be stronger.",
    "Decoration curtains and drapes are nice fabrics. More length options would serve different window sizes.",
    "Gift certificates and voucher printing is a useful service. More template designs would be welcome.",
    "Crystal frames as milestone celebration gifts work perfectly. Engraving depth could be slightly deeper.",
    "Stationery binder clips and pins are standard quality. Colored options add a nice touch.",
    "Flower garland making supplies are comprehensive. Tutorial cards with the supplies would be helpful.",
    "Photo frames corner protectors during shipping are effective. The removal doesn't damage the frame.",
    "Handicraft trivets are practical and decorative. Heat tolerance specifications would be useful to know.",
    "Flex banner finishing is clean. The hemmed edges are neat and professional looking.",
    "Decoration string lights are pretty. Weather ratings for outdoor use could be more prominent.",
    "Gift items seasonal collection arrives on time for planning. Preview catalogs earlier would be ideal.",
    "Crystal frames award quality is suitable for formal events. More size tiers would be useful.",
    "Stationery tape dispensers are functional. Weighted bases on desktop models would prevent tipping.",
    "Flower items for wreaths are good quality. More winter and autumn themed options would be nice.",
    "Photo frames anti-tarnish coating works well on metallic frames. Reapplication instructions would help.",
    "Handicraft fabric items have nice textures. Color fastness after washing varies between products.",
    "Flex banners for food stalls are food-safe. Cleaning instructions for stained banners would be useful.",
    "Decoration planters are attractive. Self-watering versions would be a great addition to the range.",
    "Gift items personalization service is a nice touch. More font and design options would improve it.",
    "Crystal frames catch light differently in various settings. A lighting guide would help buyers choose.",
    "Stationery correction products work effectively. The range covers most common office needs.",
    "Flower items for hat decorations are delicate and pretty. More vintage style options would be lovely.",
    "Photo frames in bulk for hotels are good quality. Standardized sizing for hospitality would help.",
    "Handicraft herb planters are both useful and beautiful. Drainage design could be more efficient.",
    "Flex banners for window displays look professional. Backlit options would expand display possibilities.",
    "Decoration napkin rings are elegant. More material options like wood and ceramic would be welcome.",
    "Gift tissue paper is soft and colorful. Acid-free options for wrapping delicate items would be useful.",
    "Crystal frames dust collection can be an issue. Easy-clean coating options would be a nice feature.",
    "Stationery highlighters are bright and effective. Tip durability could be improved for heavy use.",
    "Flower pressing supplies are niche but appreciated. More craft enthusiast products would be great.",
    "Photo frames gallery wall sets are curated nicely. Layout templates included with sets are helpful.",
    "Handicraft soap dishes add character to bathrooms. Water drainage on some designs could be better.",
    "Flex banners material weight options are good. Lighter weight for tall banners would reduce sagging.",
    "Decoration snow globes are charming. More design themes would expand the collectible appeal.",
    "Gift items corporate range is professional. Industry-specific gift guides would help with selection.",
    "Crystal frames paired with LED bases create stunning displays. Power cord management could be tidier.",
    "Stationery rubber stamps are well-made. Custom stamp ordering process could be more streamlined.",
    "Flower items for cake decoration are food-safe and pretty. More realistic petal textures would improve them.",
    "Photo frames restoration-style vintage collection is lovely. Antiquing finish is well done on most pieces.",
    "Handicraft key holders are both practical and decorative. Mounting hardware quality could be better.",
    "Flex banners for gym and fitness centers look professional. Sweat-resistant coating would be useful.",
    "Decoration bookmarks from the stationery section are attractive. More literary-themed designs would sell well.",
    "Gift bags with handles are sturdy and well-made. Tissue paper color coordination packs would be helpful.",
    "Crystal frames for graduation gifts are a popular choice. Cap and gown themed options would be timely.",
    "Stationery label makers are functional. Print clarity is acceptable for basic labeling needs.",
    "Flower items seasonal availability is okay. Some popular items go out of stock during peak times.",
    "Photo frames with anti-reflective glass are a nice option. The coating could be more durable.",
    "Handicraft musical instruments are decorative and interesting. Sound quality varies between pieces.",
    "Flex banners with QR codes printed clearly. Scan readability was good at reasonable distances.",
    "Decoration jar lanterns are charming. The glass thickness could be more uniform across batches.",
    "Gift items for teacher appreciation are thoughtful. More education-themed options would be welcome.",
    "Crystal frames in hexagonal shapes are trendy. The standing angle could be slightly adjustable."
  ],

  // ─── 3-Star Reviews (170 reviews) ───
  3: [
    "BP International has a decent selection for bulk orders. Some items could use quality improvements but pricing is fair.",
    "Average experience with photo frames. They work fine for the price but don't expect premium finishing.",
    "Stationery order was okay. Some items were good quality while others felt a bit cheap. Mixed bag.",
    "Decoration items are reasonably priced. Nothing extraordinary but gets the job done for basic setups.",
    "Handicrafts had some nice pieces among average ones. Quality varies quite a bit between products.",
    "Flex banners were acceptable quality. The colors weren't as vibrant as expected but still usable.",
    "Gift items are standard wholesale fare. Some unique pieces but most are common market items.",
    "Crystal frames looked okay. The clarity wasn't as high as I hoped but they're fine for the price.",
    "Flower items were decent. Some looked realistic while others clearly looked artificial.",
    "Bulk order experience was average. Delivery was on time but communication could be more proactive.",
    "Photo frames are functional. The variety is okay but nothing that really stands out from competitors.",
    "Stationery quality is passable for basic use. Premium buyers might want to look elsewhere.",
    "Decoration items served their purpose. Some pieces had minor defects but most were acceptable.",
    "Handicraft selection is okay. The traditional pieces are better quality than the modern ones.",
    "Flex banners printed adequately. Resolution was fine from a distance but up close could be better.",
    "Gift items packaging was basic. Would need to repackage most items for retail display.",
    "Crystal frames are mid-range quality. They look nice in dim lighting but show imperfections in bright light.",
    "Flower garlands were standard quality. They work for temporary decorations but won't last long-term.",
    "Stationery pens write okay. Ink quality is average and some ran dry faster than expected.",
    "Decoration lighting was functional. Nothing fancy but adequate for basic illumination needs.",
    "Photo frames glass quality was average. Fingerprints show easily and need frequent cleaning.",
    "Handicraft items had character but some had visible glue marks and uneven surfaces.",
    "Flex banner material is standard. Not the thickest but acceptable for short-term use.",
    "Gift items are what you'd expect at this price point. Some pleasant surprises, some disappointments.",
    "Crystal frames base stability is average. They work on flat surfaces but wobble slightly on textured ones.",
    "Flower items color range is limited. Basic colors are available but specialty shades are hard to find.",
    "Stationery notebooks are okay. Paper quality is thin but acceptable for everyday notes.",
    "Decoration curtains are average quality. The fabric isn't as heavy as it looked in photos.",
    "Photo frames mounting hardware is basic. Works for lightweight frames but I'd upgrade for heavier ones.",
    "Handicraft candles burn okay. Scent throw is mild and burn time is shorter than some alternatives.",
    "Flex banners are a middle-of-the-road option. Pricing is competitive which helps offset average quality.",
    "Gift bags are thin but functional. They work for lighter items but can tear with heavier gifts.",
    "Crystal frames engraving was readable but lacked the crispness I was hoping for.",
    "Flower pots are basic quality. They serve their purpose without much aesthetic wow factor.",
    "Stationery adhesives are average. They stick adequately but aren't as strong as premium brands.",
    "Decoration mirrors are okay. The frame quality is average but the mirror itself is clear enough.",
    "Photo frames in plastic are lightweight and affordable but feel a bit flimsy.",
    "Handicraft items had some paint inconsistencies. Not terrible but noticeable on close inspection.",
    "Flex banner colors faded a bit after a month of outdoor exposure. Indoor use would be fine.",
    "Gift wrapping paper is thin. It tears easily during wrapping so you need to be careful.",
    "Crystal frames are basic but functional. Don't expect high-end luxury at these prices.",
    "Flower items stems are a bit rigid. Arranging them into natural-looking displays takes some effort.",
    "Stationery rulers are adequate. Markings are clear enough for everyday use.",
    "Decoration items for outdoor use are okay but won't last through harsh weather.",
    "Photo frames arrived with one out of ten having a minor defect. Not terrible odds for bulk.",
    "Handicraft items shipping took longer than expected but they arrived in reasonable condition.",
    "Flex banners are nothing fancy but they communicate the message effectively at a fair price.",
    "Gift items for wedding favors were average. A few pieces were nicer than others in the same batch.",
    "Crystal frames weight is lighter than expected. Could go either way depending on preference.",
    "Flower items for funeral arrangements were adequate. Nothing particularly memorable but serviceable.",
    "Stationery filing supplies are basic but functional. They organize papers without breaking the bank.",
    "Decoration table accessories are simple. Fine for casual settings, might not suit formal events.",
    "Photo frames finish quality varies. Some are smooth and polished, others have slight roughness.",
    "Handicraft boxes have charm but the hinges feel like they might loosen over time.",
    "Flex banners for indoor events are fine. The material is thin enough to hang easily.",
    "Gift items variety is okay. Standard wholesale selection without many unique or standout products.",
    "Crystal frames transparency is decent. Some have slight tinting that affects the pure crystal look.",
    "Flower items packing was adequate. Most survived shipping without damage, a few needed readjusting.",
    "Stationery markers are average performers. Colors are decent but ink longevity could be better.",
    "Decoration items are mid-range. They fill a space adequately without drawing special attention.",
    "Photo frames in bulk pricing is fair for the quality level. Not the cheapest but not overpriced.",
    "Handicraft textiles have interesting patterns. Thread quality varies between pieces in the same batch.",
    "Flex banners printing alignment was slightly off on a couple. Most were centered correctly.",
    "Gift boxes closure mechanisms are okay. Magnetic closures on premium ones work well.",
    "Crystal frames as desk ornaments are acceptable. They serve the purpose without being impressive.",
    "Flower items for arts and crafts use are fine. Students found them workable for school projects.",
    "Stationery tape quality is standard. Nothing to complain about but nothing to praise either.",
    "Decoration pillows are okay quality. The stuffing flattens a bit faster than higher-end options.",
    "Photo frames corner joints are average. Most are tight enough but a few had slight gaps.",
    "Handicraft wind chimes sound okay. Not as melodious as hand-tuned ones but pleasant enough.",
    "Flex banners are serviceable for the price. You get what you pay for — nothing more, nothing less.",
    "Gift tissue paper is acceptable. Standard thickness and color selection for basic gift wrapping.",
    "Crystal frames gift boxes are functional but plain. Gift presentation could be elevated.",
    "Flower items for hair accessories are okay. Some designs look pretty while others are too simple.",
    "Stationery compass and geometry sets are functional. Precision is adequate for school-level use.",
    "Decoration wall hangings are standard. They fill wall space without adding much design character.",
    "Photo frames with clip attachments work okay. The tension in clips loosens after several uses.",
    "Handicraft coasters protect surfaces fine. Cork quality on backing is average.",
    "Flex banners waterproofing is okay for light rain. Heavy downpours might cause ink bleeding.",
    "Gift items seasonal range is standard. Similar to what you'd find at other wholesale suppliers.",
    "Crystal frames for certificates are decent. They present documents acceptably for office settings.",
    "Flower items realism varies. Premium line is convincing but budget line looks obviously artificial.",
    "Stationery pencil quality is average. Graphite hardness is consistent but wood casing splits sometimes.",
    "Decoration fabrics have okay texture. For temporary decoration purposes they work fine.",
    "Photo frames color accuracy in metallic finishes is close to photos but not exact.",
    "Handicraft pottery glazing is inconsistent. Some pieces are beautifully done, others are uneven.",
    "Flex banners hem quality is adequate. Stitching is functional but not perfectly straight throughout.",
    "Gift bags design options are limited. Basic solid colors and a few patterned options available.",
    "Crystal frames are an okay choice for budget-conscious buyers. They look respectable on a shelf.",
    "Flower items for outdoor decor last about a season before fading. Acceptable for the price.",
    "Stationery erasers work adequately. No smearing issues but they leave a bit of residue.",
    "Decoration planters are functional. Not the most stylish but they hold plants without issues.",
    "Photo frames back easel stability is average. Fine for lightweight photos on stable surfaces.",
    "Handicraft magnets are fun novelty items. The magnetic strength could be a bit stronger.",
    "Flex banners are a fine option for businesses on a budget. Don't expect signage store quality.",
    "Gift items presentation is okay. With some additional wrapping effort they can look nice.",
    "Crystal frames are average for their category. They serve the purpose without exceeding expectations.",
    "Flower items arrangement supplies are basic. Enough to get started but professionals may need more.",
    "Stationery document holders are functional. Build quality is adequate for light to moderate use.",
    "Decoration items for party planning are okay. They create atmosphere without overwhelming.",
    "Photo frames online catalog gives a rough idea but colors may differ slightly in person.",
    "Handicraft photo albums have nice covers. The page quality inside is average though.",
    "Flex banners turnaround time is average. Not the fastest but acceptable for non-urgent projects.",
    "Gift wrapping bows are okay. They hold their shape for a while before drooping slightly.",
    "Crystal frames for photo displays do the job. The photo insert process could be simpler.",
    "Flower items for wedding arch decoration are passable. They create the desired effect from a distance.",
    "Stationery scissors cut well initially. The blade edge dulls a bit faster than premium options.",
    "Decoration table runners are acceptable. The fabric is lighter than expected but looks okay.",
    "Photo frames in shadow box style have average depth. Deep items might not fit perfectly.",
    "Handicraft doorstops are functional with interesting designs. Weight distribution could be better.",
    "Flex banners for restaurant menus are readable. Lamination quality is standard.",
    "Gift items for party favors are cheap-feeling but appropriate for the price point.",
    "Crystal frames desk clock combination is functional. Clock mechanism accuracy is acceptable.",
    "Flower items for scrapbooking are flat enough to work with. The selection is limited though.",
    "Stationery labels print clearly. Adhesive quality is okay but premium labels would stick better.",
    "Decoration snow flake ornaments are average. They look fine on a tree among other decorations.",
    "Photo frames economy line is truly basic. Fine for temporary displays or student housing.",
    "Handicraft pen holders are cute. Functional enough for a desk but not premium quality.",
    "Flex banners retractable stands are workable. The retraction mechanism is a bit stiff at first.",
    "Gift boxes in economy range are thin but serviceable. Don't overload them with heavy items.",
    "Crystal frames with built-in LED are a nice concept. LED brightness is moderate, not dazzling.",
    "Flower items for corsages are basic. With some additional ribbon work they look acceptable.",
    "Stationery binders hold papers securely. The ring mechanism is average quality.",
    "Decoration couch throws are soft enough. They add color to a room without being luxurious.",
    "Photo frames collage style boards are fun. The arrangement layout options are limited though.",
    "Handicraft key chains are average quality novelty items. Good enough for souvenir shops.",
    "Flex banners reflective options for nighttime visibility are available but effectiveness varies.",
    "Gift items mix of quality makes it hard to consistently predict what you'll get in bulk.",
    "Crystal frames in colored glass variants are interesting. Color consistency between batches varies.",
    "Flower items artificial grass mats are okay for small display areas. Edges could be neater.",
    "Stationery whiteboard markers erase cleanly most of the time. Some ghost after extended display.",
    "Decoration bird houses are decorative only. Not weatherproofed enough for actual outdoor bird use.",
    "Photo frames digital printing service is available. Quality is acceptable for everyday photos.",
    "Handicraft incense sticks have mild fragrance. Burn time is shorter than some specialty brands.",
    "Flex banners mesh option for windy areas is a smart product. Airflow through material is adequate.",
    "Gift items novelty section has some fun finds mixed with forgettable items.",
    "Crystal frames are satisfactory for their wholesale price segment. Expectations should be calibrated.",
    "Flower items mixed bouquet sets give okay variety. Some flowers in the set look better than others.",
    "Stationery paper clips do their job. Nothing special but they hold papers together reliably.",
    "Decoration candle sets burn evenly. Fragrance is light which some may prefer.",
    "Photo frames for commercial displays are adequate. The bulk pricing helps justify the average quality.",
    "Handicraft greeting card blanks are decent. The paper weight is okay for most craft projects.",
    "Flex banners for temporary signage accomplish the basic goal effectively at a fair cost.",
    "Gift wrap rolls have decent length. Paper thickness is on the thinner side but manageable.",
    "Crystal frames are okay as everyday decorative items. Not luxury but presentable for most settings.",
    "Flower items for event centerpieces are acceptable. They look better arranged in groups.",
    "Stationery notepads have enough sheets for daily use. Perforation for tearing pages could be cleaner.",
    "Decoration throw pillow inserts are standard fill. Fluffiness reduces after a few weeks.",
    "Photo frames mounting adhesive strips included are okay. I'd still use wall hooks for security.",
    "Handicraft wooden toys are safe and functional. Paint finishing is basic but non-toxic.",
    "Flex banners single-sided print is clear. Double-sided option is available but alignment can be off.",
    "Gift items bulk buying from BP International is neither the best nor worst experience we've had.",
    "Crystal frames care instructions included would be helpful. Basic cleaning keeps them looking decent.",
    "Flower items foliage fillers are average. They add volume to arrangements without standing out.",
    "Stationery staplers are functional. Loading mechanism could be more intuitive for first-time users.",
    "Decoration string art kits are a nice idea. Instruction clarity could be improved for beginners.",
    "Stationery washi tape selection is basic. More pattern variety would appeal to craft enthusiasts.",
    "Flower items in autumn colors are limited. Expanding seasonal color ranges would be helpful.",
    "Photo frames with built-in easels are adequate. The hinge stiffness could be more consistent.",
    "Handicraft painted stones are fun novelty items. Paint durability on handled items is average.",
    "Flex banners for charity events were okay. Donation-related template designs would be useful.",
    "Decoration fairy garden accessories are cute. The scale consistency between items varies a bit.",
    "Gift items for housewarming are decent. A curated housewarming bundle option would be convenient.",
    "Crystal frames as photo booth props are fun but fragile. Sturdier event-grade options would help."
  ]
};

/**
 * Get a randomized subset of mock reviews for a given rating.
 * @param {number} rating - Star rating (3, 4, or 5)
 * @param {number} count - Number of reviews to return (default 5)
 * @returns {string[]} Array of review strings
 */
function getMockReviews(rating, count = 5) {
  const clampedRating = Math.max(3, Math.min(5, rating));
  const pool = MOCK_REVIEWS[clampedRating];

  if (!pool || pool.length === 0) return [];

  // Fisher-Yates shuffle on a copy, then take the first `count`
  const shuffled = [...pool];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }

  return shuffled.slice(0, Math.min(count, shuffled.length));
}
